widefix/pocketmoney

app/views/layouts/application.html.erb
I wish the earth would swallow me up!
=> fit(logo): fix the logo name

app/controllers/application_controller.rb, app/controllers/objectives_controller.rb, app/views/accounts/_objective.html.slim, app/views/accounts/show.html.slim, app/views/objectives/new.html.slim, app/views/public_account_shares/_objective.html.slim, app/views/public_account_shares/show.html.slim, db/migrate/20230918195104_remove_image_url_from_objectives.rb, db/schema.rb
Amount, Progress, Weeks to goal.
Remove the image_url field
=> feat(objectives): update fields

app/controllers/users/registrations_controller.rb, app/controllers/wizards_controller.rb, app/views/wizards/new_account.html.slim, app/views/wizards/new_automatic_topup.html.slim, app/views/wizards/new_objective.html.slim, app/views/wizards/new_share_account.html.slim, config/routes.rb, spec/controllers/wizards_controller_spec.rb
=> feat(wizard): add after signup wizard

app/javascript/menu/navbar.js
The burger didn't work with some screen resolutions
=> fix(navbar-burger): restore navbar-burger behavior

app/models/user.rb, spec/factories/access_token.rb
increase the number of characters for the user name attr
=> fix(factory): fix the name length in access token

app/views/accounts/show.html.slim, spec/features/account_spec.rb
=> feat(add links): replace the add links with a buttons

app/controllers/my_accounts_controller.rb, app/views/accounts/show.html.slim, app/views/my_accounts/show.html.slim
=> feat(archive button): hide "archive" and "archived accounts" buttons

app/views/spends/new.html.slim
=> feat(spend money): add the instruction

app/assets/stylesheets/application.scss, app/views/accounts/_objective.html.slim, app/views/accounts/show.html.slim, spec/features/account_spec.rb
=> fix(account page): fix the appearance

app/views/layouts/application.html.erb
=> fix(navbar): bring back non-transparency

app/views/my_accounts/show.html.slim
=> fix(my accounts page): fix add account button method

app/controllers/terminate_shared_account_controller.rb, app/models/account_share.rb, app/views/account_shares/_account_share.html.slim, app/views/accounts/show.html.slim, config/routes.rb, spec/controllers/terminate_shared_account_spec.rb, spec/features/account_spec.rb
=> feat(invitee): terminate shared account

app/views/accounts/show.html.slim
It was on the mobile account page
=> fix(account page): fix the agg-shaped avatar

app/assets/images/chart.svg, app/assets/stylesheets/application.scss, app/views/account_automatic_topup_configs/edit.html.slim, app/views/account_automatic_topup_configs/new.html.slim, app/views/accounts/_accumulative_balance.html.slim, app/views/accounts/new.html.slim, app/views/accounts/show.html.slim, app/views/public_account_shares/_accumulative_balance.html.slim, app/views/public_account_shares/_objective.html.slim, app/views/public_account_shares/_transaction.html.slim, app/views/public_account_shares/show.html.slim, spec/features/public_account_share_spec.rb
=> fix(public-accounts): fix style

app/javascript/image/loadAccountBackground.js, app/views/accounts/edit.html.slim
=> fix(account): fix background image javascript

app/views/accounts/edit.html.slim, spec/models/account_spec.rb
ActionView::Template::Error undefined method `persisted?' for nil:NilClass
=> fix(account): hotfix account edit

app/assets/stylesheets/application.scss, app/views/accounts/_transaction.html.slim, app/views/accounts/show.html.slim, app/views/public_account_shares/_transaction.html.slim, app/views/public_account_shares/show.html.slim
=> feat(account): add scroll for transactions and goals

app/models/user.rb, app/views/accounts/show.html.slim
=> fix(account page): fix account owner visibility

app/javascript/account/accomplishedGoals.js
=> fix(accomplished goals) fix TypeError

app/views/spends/_modal.html.slim, app/views/topups/_modal.html.slim
=> fix(madals): add margin
